php7-fpm:
    image: bopoh24/php7-fpm
    restart: always
    container_name: php7-fpm
    net: host
    volumes:
      - .:/app
      - ./docker/configs/php/fpm/php.ini:/etc/php/7.0/fpm/php.ini
      - ./docker/configs/php/fpm/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./docker/configs/php/fpm/pool.d/www.conf:/etc/php/7.0/fpm/pool.d/www.conf

nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
        - .:/app
        - ./docker/configs/nginx/sites-enabled/itrend_ai:/etc/nginx/sites-enabled/itrend_ai
        - ./docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro